services:
  ipwrc-back:
    build:
      context: ./IPWRC-Back
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  ipwrc-front:
    build:
      context: ./IPWRC-Front
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - ipwrc-back
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
