spring.datasource.url=jdbc:postgresql://dpg-d3ucn3je5dus739j85kg-a.frankfurt-postgres.render.com:5432/ipwrc_mppv?sslmode=require
spring.datasource.username=ipwrcuser
spring.datasource.password=9yGHzq30IaPKbtMsuEPvbBeYPei09jjB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true